/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jskj.asset.client.panel.message;

import com.jskj.asset.client.bean.MessageCacheBean;
import com.jskj.asset.client.bean.PathCacheBean;
import com.jskj.asset.client.layout.BasePanel;
import com.jskj.asset.client.layout.BaseTextField;
import com.jskj.asset.client.layout.IPopupBuilder;
import com.jskj.asset.client.layout.PopupButton;
import com.jskj.asset.client.util.DateHelper;
import com.jskj.asset.client.util.XMLHelper;
import java.util.Date;
import java.util.logging.Level;
import javax.xml.bind.JAXBException;
import org.apache.log4j.Logger;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;

/**
 *
 * @author 305027939
 */
public abstract class MessageConfig extends BasePanel {

    private final static Logger logger = Logger.getLogger(MessageConfig.class);
    private PopupButton panel;
    private MessageCacheBean messageCacheBean;

    /**
     * Creates new form MessageConfig
     *
     * @param panel
     */
    public MessageConfig(PopupButton panel) {
        this.panel = panel;
        initComponents();
        messageCacheBean = new MessageCacheBean();
        ((BaseTextField) jTextFieldDate).registerPopup(IPopupBuilder.TYPE_DATE_CLICK, "yyyy-MM-dd");

        ((BaseTextField) jTextFieldShenpihouDate).registerPopup(IPopupBuilder.TYPE_DATE_CLICK, "yyyy-MM-dd");

        //得到一月中的日期
        jTextFieldDate.setText(DateHelper.format(DateHelper.currentDateAdd(-30), "yyyy-MM-dd"));

        //得到15中天内的数据
        jTextFieldShenpihouDate.setText(DateHelper.format(DateHelper.currentDateAdd(-15), "yyyy-MM-dd"));

        readCache();
    }

    private void readCache() {
        XMLHelper<MessageCacheBean> helper = new XMLHelper<MessageCacheBean>(messageCacheBean);
        try {
            messageCacheBean = helper.read();

            jCheckBoxTask.setSelected(messageCacheBean.isDisplayMyTask());

            jCheckBoxShenpihou.setSelected(messageCacheBean.isDisplayMyShenpi());

            if (messageCacheBean.getSec() >= 0) {
                jComboBoxSec.setSelectedIndex(messageCacheBean.getSec());
                jCheckBoxAuto.setSelected(messageCacheBean.isAutoUpdate());
            }
            jCheckBoxApp.setSelected(messageCacheBean.isDisplayMyApp());

        } catch (JAXBException ex) {
            logger.error(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCheckBoxAuto = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxSec = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jCheckBoxTask = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jCheckBoxApp = new javax.swing.JCheckBox();
        jTextFieldDate = new BaseTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jCheckBoxShenpihou = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldShenpihouDate = new BaseTextField();
        jLabel6 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setName("Form"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.jskj.asset.client.AssetClientApp.class).getContext().getResourceMap(MessageConfig.class);
        jPanel1.setFont(resourceMap.getFont("jPanel1.font")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jCheckBoxAuto.setFont(resourceMap.getFont("jCheckBoxAuto.font")); // NOI18N
        jCheckBoxAuto.setSelected(true);
        jCheckBoxAuto.setText(resourceMap.getString("jCheckBoxAuto.text")); // NOI18N
        jCheckBoxAuto.setName("jCheckBoxAuto"); // NOI18N

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jComboBoxSec.setFont(resourceMap.getFont("jComboBoxSec.font")); // NOI18N
        jComboBoxSec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5", "10", "30", "60", "120", "300", "600", " " }));
        jComboBoxSec.setSelectedIndex(2);
        jComboBoxSec.setName("jComboBoxSec"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxAuto)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxSec, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jCheckBoxAuto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.jskj.asset.client.AssetClientApp.class).getContext().getActionMap(MessageConfig.class, this);
        jButton1.setAction(actionMap.get("save")); // NOI18N
        jButton1.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jCheckBoxTask.setFont(resourceMap.getFont("jCheckBoxTask.font")); // NOI18N
        jCheckBoxTask.setSelected(true);
        jCheckBoxTask.setText(resourceMap.getString("jCheckBoxTask.text")); // NOI18N
        jCheckBoxTask.setName("jCheckBoxTask"); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setName("jPanel2"); // NOI18N

        jCheckBoxApp.setFont(resourceMap.getFont("jCheckBoxApp.font")); // NOI18N
        jCheckBoxApp.setSelected(true);
        jCheckBoxApp.setText(resourceMap.getString("jCheckBoxApp.text")); // NOI18N
        jCheckBoxApp.setName("jCheckBoxApp"); // NOI18N

        jTextFieldDate.setText(resourceMap.getString("jTextFieldDate.text")); // NOI18N
        jTextFieldDate.setName("jTextFieldDate"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(jCheckBoxApp))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxApp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setName("jPanel3"); // NOI18N

        jCheckBoxShenpihou.setFont(resourceMap.getFont("jCheckBoxShenpihou.font")); // NOI18N
        jCheckBoxShenpihou.setSelected(true);
        jCheckBoxShenpihou.setText(resourceMap.getString("jCheckBoxShenpihou.text")); // NOI18N
        jCheckBoxShenpihou.setName("jCheckBoxShenpihou"); // NOI18N

        jLabel5.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jTextFieldShenpihouDate.setFont(resourceMap.getFont("jTextFieldShenpihouDate.font")); // NOI18N
        jTextFieldShenpihouDate.setText(resourceMap.getString("jTextFieldShenpihouDate.text")); // NOI18N
        jTextFieldShenpihouDate.setName("jTextFieldShenpihouDate"); // NOI18N

        jLabel6.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBoxShenpihou)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldShenpihouDate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxShenpihou)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldShenpihouDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBoxTask, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxTask)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(7, 7, 7))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxApp;
    private javax.swing.JCheckBox jCheckBoxAuto;
    private javax.swing.JCheckBox jCheckBoxShenpihou;
    private javax.swing.JCheckBox jCheckBoxTask;
    private javax.swing.JComboBox jComboBoxSec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldDate;
    private javax.swing.JTextField jTextFieldShenpihouDate;
    // End of variables declaration//GEN-END:variables

    @Override
    public Task reload() {
        return null;
    }

    @Override
    public Task reload(Object param) {
        return null;
    }

    public abstract void savedData(Date startDate, Date startShenpiDate, boolean autorefresh, final int selectSec, boolean displayTask, boolean displayApplication, boolean displayShenpi);

    @Action
    public void save() {
        String date = jTextFieldDate.getText();
        String shenpidate = jTextFieldShenpihouDate.getText();
        Date selectDate = DateHelper.getStringtoDate(date, "yyyy-MM-dd");
        Date selectShenpiDate = DateHelper.getStringtoDate(shenpidate, "yyyy-MM-dd");
        boolean autorefresh = jCheckBoxAuto.isSelected();
        int selectSec = Integer.parseInt(jComboBoxSec.getSelectedItem().toString());
        logger.debug("calculation message data before " + date);
        savedData(selectDate, selectShenpiDate, autorefresh, selectSec, jCheckBoxTask.isSelected(), jCheckBoxApp.isSelected(), jCheckBoxShenpihou.isSelected());
        panel.hidePanel();

        try {
            messageCacheBean.setAutoUpdate(autorefresh);
            messageCacheBean.setSec(jComboBoxSec.getSelectedIndex());
            messageCacheBean.setDisplayMyApp(jCheckBoxApp.isSelected());
            messageCacheBean.setDisplayMyShenpi(jCheckBoxShenpihou.isSelected());
            messageCacheBean.setDisplayMyTask(jCheckBoxTask.isSelected());
//            messageCacheBean.setShenpidanDate(shenpidate);
//            messageCacheBean.setShenqingdanDate(date);
            XMLHelper<MessageCacheBean> helper = new XMLHelper<MessageCacheBean>(messageCacheBean);
            helper.write();
        } catch (JAXBException ex) {
            logger.error(ex);
        }

    }
}
