/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jskj.asset.client.login;

import com.jskj.asset.client.AssetClientApp;
import com.jskj.asset.client.bean.PathCacheBean;
import com.jskj.asset.client.bean.PathCacheBean.PathBean;
import com.jskj.asset.client.bean.UserSessionEntity;
import com.jskj.asset.client.bean.entity.Usertb;
import com.jskj.asset.client.constants.Constants;
import com.jskj.asset.client.util.XMLHelper;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import org.jdesktop.application.Action;
import org.jdesktop.application.Application;
import org.jdesktop.application.Task;

/**
 *
 * @author 305027939
 */
public class LoginMain extends javax.swing.JFrame {

    private String[] args;

    private boolean logined = false;

    
    /**
     * Creates new form LoginMain
     */
    public LoginMain(String[] args) {
        initComponents();
        this.args = args;

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int y = screenSize.height / 2 - getHeight() / 2;
        int x = screenSize.width / 2 - getWidth() / 2;
        setBounds(x, y, Constants.LOGIN_WIDTH, Constants.LOGIN_HEIGHT);
        Dimension windowPop = new Dimension(354, 326);
        setMaximumSize(windowPop);
        setMinimumSize(windowPop);
        setTitle(Constants.WINTITLE);
        setResizable(false);
        new LoginInfoTask(LoginInfoTask.READ_XML).execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userNameFiled = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        passwordFiled = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        serviceText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        portText = new javax.swing.JTextField();
        warningMsg = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(361, 326));
        setName("Form"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jskj/asset/client/login/resources/logo.jpg"))); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel2.setFont(Constants.GLOBAL_FONT);
        jLabel2.setText("用户名:"); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setFont(Constants.GLOBAL_FONT);
        jLabel3.setText("密码:"); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.jskj.asset.client.AssetClientApp.class).getContext().getResourceMap(LoginMain.class);
        userNameFiled.setText(resourceMap.getString("userNameFiled.text")); // NOI18N
        userNameFiled.setName("userNameFiled"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.jskj.asset.client.AssetClientApp.class).getContext().getActionMap(LoginMain.class, this);
        loginButton.setAction(actionMap.get("sendLogin")); // NOI18N
        loginButton.setFont(Constants.GLOBAL_FONT);
        loginButton.setIcon(resourceMap.getIcon("loginButton.icon")); // NOI18N
        loginButton.setName("loginButton"); // NOI18N

        jButton1.setAction(actionMap.get("close")); // NOI18N
        jButton1.setFont(Constants.GLOBAL_FONT);
        jButton1.setName("jButton1"); // NOI18N

        passwordFiled.setText(resourceMap.getString("passwordFiled.text")); // NOI18N
        passwordFiled.setName("passwordFiled"); // NOI18N
        passwordFiled.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordFiledKeyReleased(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setName("jPanel2"); // NOI18N

        jLabel4.setFont(new java.awt.Font("宋体", 0, 12)); // NOI18N
        jLabel4.setText("服务器:"); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        serviceText.setText(resourceMap.getString("serviceText.text")); // NOI18N
        serviceText.setName("serviceText"); // NOI18N

        jLabel5.setFont(new java.awt.Font("宋体", 0, 12)); // NOI18N
        jLabel5.setText("端口:"); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        portText.setText(resourceMap.getString("portText.text")); // NOI18N
        portText.setName("portText"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serviceText, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(portText, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(serviceText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5)
                .addComponent(portText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        warningMsg.setFont(new java.awt.Font("宋体", 1, 12)); // NOI18N
        warningMsg.setForeground(new java.awt.Color(255, 0, 0));
        warningMsg.setName("warningMsg"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(warningMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(loginButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(userNameFiled)
                                    .addComponent(passwordFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(warningMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        versionLabel.setFont(resourceMap.getFont("versionLabel.font")); // NOI18N
        versionLabel.setText("version 1.00"); // NOI18N
        versionLabel.setName("versionLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(versionLabel)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(versionLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordFiledKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFiledKeyReleased
        int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_ENTER) {
            sendLogin().execute();
        }
    }//GEN-LAST:event_passwordFiledKeyReleased

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LoginMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LoginMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LoginMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LoginMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoginMain().setVisible(true);
//            }
//        });
//    }
    private void setWarningMsg(String mgs) {
        warningMsg.setText(mgs);
        Thread one1 = new Thread(new Runnable() {
            public void run() {
                try {
                    Thread.sleep(10000);
                    warningMsg.setText("");
                } catch (InterruptedException ex) {
                }
            }

        });
        one1.start();
    }

    @Action
    public Task sendLogin() {
        String userName = userNameFiled.getText();
        String serviceAdd = serviceText.getText();
        String password = String.valueOf(passwordFiled.getPassword());
        if (userName.trim().equals("")) {
            setWarningMsg("请输入用户名!");
            userNameFiled.grabFocus();
            return null;
        }

        if (serviceAdd.trim().equals("")) {
            setWarningMsg("请输入服务端IP!");
            serviceText.grabFocus();
            return null;
        }

        setWarningMsg("");
        new LoginInfoTask(LoginInfoTask.WRITE_XML).execute();

        HashMap map = new HashMap();
        map.put("userName", userName);
        map.put("userPassword", password);
        loginButton.setEnabled(false);
        return new SendLoginTask(map);
    }

    private class LoginInfoTask extends Task<Object, Void> {

        public final static int READ_XML = 0;
        public final static int WRITE_XML = 1;

        private int type = 0;

        public LoginInfoTask(int type) {
            super(Application.getInstance(AssetClientApp.class));
            this.type = type;
        }

        @Override
        protected Object doInBackground() throws Exception {
            try {
                if (type == WRITE_XML) {
                    String userName = userNameFiled.getText();
                    String password = String.valueOf(passwordFiled.getPassword());
                    String serviceAdd = serviceText.getText();
                    String port = portText.getText();

                    Constants.setHTTPHost(serviceAdd, port);

                    PathCacheBean pathBeans = new PathCacheBean();
                    List<PathBean> maps = new ArrayList<PathBean>();
                    PathCacheBean.PathBean nameMap = new PathCacheBean.PathBean();
                    nameMap.setKey("username");
                    nameMap.setValue(userName);
                    maps.add(nameMap);
                    PathCacheBean.PathBean serverMap = new PathCacheBean.PathBean();
                    serverMap.setKey("server");
                    serverMap.setValue(serviceAdd);
                    maps.add(serverMap);
                    PathCacheBean.PathBean portMap = new PathCacheBean.PathBean();
                    portMap.setKey("port");
                    portMap.setValue(port);
                    maps.add(portMap);

                    pathBeans.setPaths(maps);

                    XMLHelper<PathCacheBean> helper = new XMLHelper<PathCacheBean>(pathBeans);
                    helper.write();
                } else {
                    XMLHelper<PathCacheBean> helper = new XMLHelper<PathCacheBean>(new PathCacheBean());
                    PathCacheBean paths = helper.read();
                    List<PathBean> pathBeans = paths.getPaths();
                    if (pathBeans != null) {
                        for (PathBean bean : pathBeans) {
                            String key = bean.getKey();
                            if (key.equalsIgnoreCase("username")) {
                                userNameFiled.setText(bean.getValue());
                            } else if (key.equalsIgnoreCase("server")) {
                                serviceText.setText(bean.getValue());
                            } else if (key.equalsIgnoreCase("port")) {
                                portText.setText(bean.getValue());
                            }
                        }
                        passwordFiled.grabFocus();
                    }

                }
            } catch (Exception e) {
                System.err.println(e.getMessage());
            }
            return "";
        }
    }

    private class SendLoginTask extends LoginTask {

        SendLoginTask(HashMap map) {
            super(map, logined);
        }

        @Override
        public void onSucceeded(Object object) {
            loginButton.setEnabled(true);
            if (object == null) {
                setWarningMsg("服务端异常!");
                return;
            }
            if (object instanceof Exception) {
                Exception e = (Exception) object;
                setWarningMsg(e.getMessage());
                return;
            }

            if (object instanceof UserSessionEntity) {
                UserSessionEntity session = (UserSessionEntity) object;
                Usertb user = session.getUsertb();
                if (user != null) {
                    if (logined) {
                        AssetClientApp.getApplication().getMainFrame().dispose();
                    }
                    AssetClientApp.startupApplication(args, LoginMain.this, session);
                    dispose();
                    logined = true;
                } else {
                    setWarningMsg("请检查用户名和密码!");
                }
            } else {
                setWarningMsg("签入服务器异常!");
            }
        }

    }

    @Action
    public void close() {
        if (logined) {
            dispose();
        } else {
            System.exit(0);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordFiled;
    private javax.swing.JTextField portText;
    private javax.swing.JTextField serviceText;
    private javax.swing.JTextField userNameFiled;
    private javax.swing.JLabel versionLabel;
    private javax.swing.JLabel warningMsg;
    // End of variables declaration//GEN-END:variables
}
