/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jskj.asset.client.panel;

import com.jskj.asset.client.layout.AssetArrayNodes;
import com.jskj.asset.client.layout.AssetMessage;
import com.jskj.asset.client.layout.AssetNode;
import com.jskj.asset.client.layout.AssetTreeModel;
import com.jskj.asset.client.layout.AssetTreeNode;
import com.jskj.asset.client.layout.BaseTreePane;
import java.util.List;
import org.apache.log4j.Logger;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;

/**
 *
 * @author 305027939
 */
public class LeftPanel extends BaseTreePane {

    private final static Logger logger = Logger.getLogger(LeftPanel.class);

    /**
     * Creates new form LeftPanel
     */
    public LeftPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navigatorTree = new javax.swing.JTree();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.jskj.asset.client.AssetClientApp.class).getContext().getResourceMap(LeftPanel.class);
        navigatorTree.setFont(resourceMap.getFont("navigatorTree.font")); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("[Loading]");
        navigatorTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        navigatorTree.setAlignmentX(3.0F);
        navigatorTree.setAlignmentY(3.0F);
        navigatorTree.setAutoscrolls(true);
        navigatorTree.setName("navigatorTree"); // NOI18N
        navigatorTree.setRowHeight(25);
        navigatorTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navigatorTreeMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(navigatorTree, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(navigatorTree, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void navigatorTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navigatorTreeMouseClicked
        AssetTreeNode selectedNode = (AssetTreeNode) navigatorTree.getLastSelectedPathComponent();  //获取鼠标点击点
        if (selectedNode == null) {
            return;//如果不是树上的节点
        }
        if (selectedNode.isLeaf() && evt.getClickCount() == 2) { //确定是叶节点且是双//击事件。
            Task task = new OpenTabTask(selectedNode);
            task.execute();
            logger.debug("------------>TabPane:" + disTabCount);
        }
    }//GEN-LAST:event_navigatorTreeMouseClicked

    /**
     * @param navigatorTree the navigatorTree to set
     */
    public void setNavigatorTree(javax.swing.JTree navigatorTree) {
        this.navigatorTree = navigatorTree;
    }

    public javax.swing.JTree getNavigatorTree() {
        return navigatorTree;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree navigatorTree;
    // End of variables declaration//GEN-END:variables

    @Action
    @Override
    public Task reload() {
        return new NavigatorPanelTask();
    }

    class NavigatorPanelTask extends NavigatorTask {

        @Override
        public void onSucceeded(Object object) {
            if (object instanceof Exception) {
                Exception e = (Exception) object;
                AssetMessage.ERRORSYS("读取失败:" + e.getMessage());
                logger.error(e);
            } else {
                AssetArrayNodes nodes = (AssetArrayNodes) object;

                navigatorTree.setRootVisible(false);
                navigatorTree.setModel(new AssetTreeModel(getTreeNode(new AssetTreeNode(nodes.getTopNode()), nodes.getNodes())));

            }
        }

    }

    private AssetTreeNode getTreeNode(AssetTreeNode parent, List<AssetNode> nodes) {
        // DefaultMutableTreeNode treeNodeChild = null;
        if (nodes != null) {
            for (AssetNode node : nodes) {
                //DefaultMutableTreeNode treeNodeChild = new DefaultMutableTreeNode(node.getNodeName());
                AssetTreeNode treeNodeChild = new AssetTreeNode(node);
                List<AssetNode> nodeChild = node.getChildNode();
                if (nodeChild != null) {
                    getTreeNode(treeNodeChild, nodeChild);
                }
                parent.add(treeNodeChild);
            }
        }
        return parent;
    }

    @Override
    public Task reload(Object param) {
        return null;
    }
}
