/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ToppagePane.java
 *
 * Created on Jan 7, 2011, 1:27:35 PM
 */
package com.jskj.asset.client.panel;

import com.jskj.asset.client.constants.Constants;
import com.jskj.asset.client.layout.AssetMessage;
import com.jskj.asset.client.layout.BasePanel;
import com.jskj.asset.client.layout.BaseTask;
import java.io.IOException;
import org.apache.log4j.Logger;
import org.jdesktop.application.Task;

/**
 *
 * @author woderchen
 */
public class ToppagePane extends BasePanel {

    private static Logger logger = Logger.getLogger(ToppagePane.class);

    /**
     * Creates new form ToppagePane
     */
    public ToppagePane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorTopPage = new javax.swing.JEditorPane();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.jskj.asset.client.AssetClientApp.class).getContext().getResourceMap(ToppagePane.class);
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jEditorTopPage.setEditable(false);
        jEditorTopPage.setBorder(null);
        jEditorTopPage.setName("jEditorTopPage"); // NOI18N
        jScrollPane1.setViewportView(jEditorTopPage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public Task reload() {
        return new SendUrlTask();
    }

    @Override
    public Task reload(Object param) {
        return null;
    }

    private class SendUrlTask extends BaseTask {

        @Override
        public Object doBackgrounp() {
            try {
                jEditorTopPage.setPage(Constants.HTTP + "/AssetsSys/service/toppage?client");
            } catch (IOException e) {
                jEditorTopPage.setText(e.getMessage());
                AssetMessage.ERRORSYS(e.getMessage());
                logger.error(e.getMessage());
            }
            return null;
        }

        @Override
        public void onSucceeded(Object object) {
            //new GraphicTask().execute();
            //new MyTaskFindTask(messagePanel,true).execute();
        }

    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorTopPage;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
